### ISSUE TITLE
Integrate SEEALSO col from concepticon.tsv

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon#1]

**Comment by LinguList** [comment]
We can discard this, I guess, since the seealso was a shortcut to store alternative OmegaWiki-Links in cases of nearly similar concepts. Now that we introduced relations, this should be covered. Let's keep seealso, however, for a little while, since I also used them at some point to keep track on what we now plan to model as "narrower-broader"-relations, so I might want to look up and include the information before we get rid of it completely...
