### ISSUE TITLE
Link to LREC paper from the website

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon#11]
Somewhere on http://concepticon.clld.org we should add a link to the LREC paper. Any ideas, where? Maybe add an "About" page, where we would also move the acknowledgements?

**Comment by LinguList** [comment]
Yes, this is exactly what I was thinking. We could then also split the
most burning information into more specific information.

**Comment by xrotwang** [comment]
@LinguList Have a look at https://github.com/clld/concepticon/commit/7d7752ecbf9fe6af4aae3330d85cbd00519e4d56 for a first idea about how to re-arrange the content.

**Comment by LinguList** [comment]
Yes, I think this looks nice. I'd change a few wordings, but I propose
I'll do that later on, once the questions of general representation are
settled.

**Comment by xrotwang** [comment]
When do you think we should put 1.0 online?

**Comment by LinguList** [comment]
I'd suggest to wait until middle of May, or end of April, so that first
we can have some time to look at it and reflect a bit more about the
arrangment (I'm unfortunately busy with other things at the moment). But
also so that we can synchronize the publication with the LREC
conference, and send around links to Linguist list etc. at the same
time. Ideally, we would do everything at the same time, so that we could
add the reference for the LREC paper on the website, but I guess this
will have to be done later by simply exchanging the PDF or the link with
the one that appears in the proceedings.

Ah, and I forgot: contributing and examples for how to map the lists
using the scripts I used so far are things that still need to be done,
so I'd be happy enough with Middle of May, but I'd also be open to
launch it a bit earlier.

**Comment by LinguList** [comment]
I suppose we close this one now, since the current link to the paper should be okay.
