### ISSUE TITLE
Empty English gloss rows in value table

### ISSUE THREAD

**Issue by chrzyki** [clld/concepticon#34]
Given that the 'English gloss' column in https://concepticon.clld.org/values is only filled with entries from `GLOSS` in the original concept list tables, there are a lot of 'empties' in there and original columns like `ENGLISH` are not used.

While not strictly speaking problematic, this in my opinion diminishes the 'look and feel' of the values table and it feels empty. Could additional columns (`ENGLISH` etc.?) be considered if `GLOSS` is not presented? Could the appearance of the `English gloss` column be otherwise improved?

**Comment by LinguList** [comment]
So you know the rule: gloss is used to mark a translation if English is not there. Theoretically, we do not even need this, as we are reaching a level where we can link to concepticon without translating every entry, and it may sometimes even be easier and probably also better. We could probably 

* treat the English Gloss just as an elicitation gloss in any language (maybe "English translation")
* not display it
* use English in first column (gloss and translation) and add a column with the other languages
* decide on some three to four major languages to be displayed (may also look sparse)

If we treat English gloss just as an elicitation gloss translation, this may be easiest.

**Comment by chrzyki** [comment]
Thanks! I agree. Anything to make the column useful/improve the layout. :)

**Comment by xrotwang** [comment]
I agree that the "English gloss" column at https://concepticon.clld.org/values does not provide anything of value (since its content will also be available via "Description in source"). So I'd say we drop this.

And as @LinguList says, we have now a lot more coverage of glosses in languages other than English. Thus, I'd propose to do what I planned on doing for some time: promoting individual glosses to first-class clld objects, namely to `Unit`s. This would also mean we add each language that we have glosses for - which may at some point become interesting enough for its own page.

**Comment by LinguList** [comment]
Sounds good, and it could even allow us to move to a stage where we ignore the English translation, as it may at times only support the bias we already have to fight with with English as major glossing language. It would mean, we can map a list in Chinese to concepticon, without providing translations. And we might consider that we simply distinguish for a glossing language in Concepticon if it is our translation by the concepticon group, of if it is the translation in the source. But that's something to be discussed later. For now, it may be useful to mechanically distinguish the ENGLISH from the GLOSS by writing ENGLISH vs. ENGLISH translation ?

**Comment by xrotwang** [comment]
I was going to just use a "MetaLanguage" as the thing that relates concepts with concept sets. If we provided an english translation, this would be the gloss in the MetaLanguage. If an english gloss was provided by the source, this would become a regular "Gloss". The labels in the MetaLanguage would actually never show in the user interface, because they can be replaced by `CONCEPTICON_GLOSS` of the concept sets.
