### ISSUE TITLE
Compute and display metrics about Concept Lists

### ISSUE THREAD

**Issue by xrotwang** [clld/concepticon#6]
**Uniqueness** of the concept inventory within a concept list: How often do the concepts in the list occur in other lists. May be computed as
```python
sum([1/len(concept_set(c)) for c in cl]) / len(cl)
```

**Similarity** of concept lists: Which lists are most similar in terms of overlaps in concepts to the given list. May be computed via a Jaccard distance: 
```python
def similarity(cl1, cl2):
    cs1 = set(concept_set(c) for c in cl1)
    cs2 = set(concept_set(c) for c in cl2)
    return len(cs1.intersection(cs2)) / len(cs1.union(cs2))
```
Given this metric for similarity, we could display - say - the 3 most similar lists as "related" lists on the details page of a concept list.

**Comment by xrotwang** [comment]
The current top-5 regarding the uniqueness measure above are:

 name | items | uniqueness
 ---- | ----:| ----:
Borin 2012 | 40 | 0.481050187909
Bulakh 2013 | 870 | 0.378097206779
Galucio 2015 | 90 | 0.365125899772
Hou 2004 | 180 | 0.333139003001
Allen 2007 | 500 | 0.232191134706

@LinguList Does this look about right?

**Comment by LinguList** [comment]
completely! borin is a very special list on concepts that are not relevant for cross-linguistic studies but rather for some translation stuff, bulakh is full of strange specific concepts, galucio is a cultural list of concepts, hou is a Chinese dialectology list (very non-basic), and allen is a Chinese field-work list (also very special and non-basic).

**Comment by xrotwang** [comment]
And here comes the similarity top-10:

CL1 | items | CL2 | items | similarity
--- | ---:| --- | ---:| ---:
Wichmann 2010 | 40 | Holman 2008 | 40 | 1.0
Gudschinsky 1956 | 200 | Swadesh 1960 | 200 | 0.980198019802
List 2014 | 1280 | Key 2015 | 1310 | 0.980046047583
Comrie 1977 | 207 | Bowern 2008 | 207 | 0.976076555024
Wang 2006 | 200 | Chen 1996 | 200 | 0.970443349754
Starostin 1991 | 110 | Starostin 2007 | 110 | 0.964285714286
Wiktionary 2003 | 207 | Dunn 2012 | 207 | 0.962085308057
Benedict 1976 | 100 | Holman 2008 | 100 | 0.960784313725
Bowern 2008 | 207 | Dunn 2012 | 207 | 0.957345971564
Wheeler 2015 | 102 | Nahhas 2006 | 100 | 0.95145631068
Comrie 1977 | 207 | Dunn 2012 | 207 | 0.943661971831

**Comment by LinguList** [comment]
Ha, this is nice, there you immediately see who copied from whom: Chomsky-1960 is actually not Chomsky, but Hymes, who claims he has it from Chomsky, but this is obviously not the case.

Bowern and IELex lists both do not directly come from Swadesh, as usually quoted, but they go back to Comrie who was the first to publish 207 concepts, merging Swadesh, but introducing some uncertainties.

**Comment by xrotwang** [comment]
@LinguList I don't quite understand the bit about Chomsky and Hymes, but the remainder makes sense.

Btw. out of the 5995 combinations (of 110 concept lists), only about 100 have similarity 0, i.e. don't share any concept sets; which I guess is a good thing.

**Comment by LinguList** [comment]
Ah: not chomsy, but Swadesh-1960, sorry. 

Reg. your BTW: I agree, this shows it is quite consistent, and the 0 similarities will be due to small lists like dolgopolsky, and the like.

**Comment by xrotwang** [comment]
Yes, the combination with similarity 0 and the biggest sum of concepts is Dolch-1936-220 Urban-2011-160. Quite a few 100 item lists are disjoint, though.

**Comment by LinguList** [comment]
this is also to be expected, since we have a lot of 200 item list which teh authors themselve explicitly split into two parts, so that one part is more stable, and the other is supposed to be less stable. You find, for example Wang-1996-100a.tsv and Wang-1996-100b.tsv, if I'm not mistaken, these are combined in Wang-1996-200.tsv. I labelled these cases as "sublist", or as "hihi" vs. "lolo", if they do not split the full list, but just pick out two disjoint sets, one supposed to be stable (hihi, accroding to the strange terminology by McMahon et al.) and one supposed to be unstable (lolo). 

I was thinking that I should add a further column to the conceptlists.tsv to make this clearer: a see-also column, where these sublists and hihi-lolo-games with concepts are referenced. We have it already in the description of each list, but maybe, one could separate the links from it ad add an extra "see-also"...

**Comment by xrotwang** [comment]
So you want to go deeper into this rabbit hole, adding `conceptlistrelations.tsv`?

**Comment by LinguList** [comment]
Oh no, this would be way too much. I was trying to compute them before, since I wanted to know who pasted from whom (which is often quite obvious), but it's leading too far...

But from the refs in the notes, one can already create automatically some kind of relations, although they are based on my annotations.

**Comment by LinguList** [comment]
And I guess, one could write a nice paper on the "history of concept lists". There are so many cases of scientific sloppyness to be found, where people quote Swadesh but actually paste from somebody else. It's not only a rabbit whole, it's a dungeon full of dragons!
